### ISSUE TITLE
Solving delete poll element hover bug

### ISSUE THREAD

**Issue by arthur-caillaud** [ApricoTeam/aprico-front#19]

**Comment by larmx** [comment]
@arthur-caillaud Could you provide a small description of the bug? Thanks!

**Comment by arthur-caillaud** [comment]
<img width="359" alt="capture d ecran 2018-07-10 a 19 03 54" src="https://user-images.githubusercontent.com/24208801/42546828-061fcea6-8474-11e8-861a-8f6c321dc3ba.png">
<img width="358" alt="capture d ecran 2018-07-10 a 19 03 47" src="https://user-images.githubusercontent.com/24208801/42546829-063b83e4-8474-11e8-9be4-016262696a7c.png">

**Comment by arthur-caillaud** [comment]
After having deleted one element, the hover is broken for every other elements. Do you store it in redux ? If yes, I don't think it's necessary @larmx

**Comment by arthur-caillaud** [comment]
(you can see that I am hovering the first element in the first picture and the second element in the second picture)
